---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "cerner_integration"
  name: "cerner-integrat"
spec:
  ports:
  - name: "port-1-cerner-i"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
  - name: "port-2-cerner-i"
    port: 9091
    protocol: "TCP"
    targetPort: 9091
  selector:
    app: "cerner_integration"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "config-config-map"
data:
  Config.toml: "\n# Configuration file for \"cerner_integration\"\n# \n# This file\
    \ contains configuration values for configurable variables in your Ballerina code.\n\
    # Both package-specific and imported module configurations are included below.\n\
    # \n# Learn more about configurable variables:\n# https://ballerina.io/learn/provide-values-to-configurable-variables/#provide-via-toml-syntax\n\
    #\n# Note: This file is automatically added to .gitignore to protect sensitive\
    \ information. \n\nbase = \"https://fhir-ehr-code.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d\"\
    \ntokenUrl = \"https://authorization.cerner.com/tenants/ec2458f2-1e24-41c8-b71b-0e701af7583d/protocols/oauth2/profiles/smart-v1/token\"\
    \nclientId = \"977f278f-eb3f-411e-b2ff-16c554501d69\"\nclientSecret = \"AW0nwz9LqNrb_pTzxUHsbqey1f0bzRv_\"\
    \n\n# baseUrl = \"https://fhir-ehr-code.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d\"\
    \n# tokenUrls = \"https://authorization.cerner.com/tenants/ec2458f2-1e24-41c8-b71b-0e701af7583d/protocols/oauth2/profiles/smart-v1/token\"\
    \n# clientIdValue = \"977f278f-eb3f-411e-b2ff-16c554501d69\"\n# clientSecretValue\
    \ = \"AW0nwz9LqNrb_pTzxUHsbqey1f0bzRv_\"\n\n\n"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "cerner_integration"
  name: "cerner-integrat-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cerner_integration"
  template:
    metadata:
      labels:
        app: "cerner_integration"
    spec:
      containers:
      - env:
        - name: "BAL_CONFIG_FILES"
          value: "/home/ballerina/conf/Config.toml:"
        image: "mohanvive/cerner-integration:latest"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "cerner-integrat-deployment"
        ports:
        - containerPort: 9090
          name: "port-1-cerner-i"
          protocol: "TCP"
        - containerPort: 9091
          name: "port-2-cerner-i"
          protocol: "TCP"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/home/ballerina/conf/"
          name: "config-config-map-volume"
          readOnly: false
      volumes:
      - configMap:
          name: "config-config-map"
        name: "config-config-map-volume"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  labels:
    app: "cerner_integration"
  name: "cerner-integrat"
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: "cpu"
      target:
        averageUtilization: 50
        type: "Utilization"
    type: "Resource"
  minReplicas: 1
  scaleTargetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "cerner-integrat-deployment"
