name: Ballerina CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ballerina
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.12.2 # Specify the Ballerina version

      - name: Cache Ballerina Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.ballerina
          key: ballerina-deps-${{ hashFiles('**/Ballerina.toml') }}
          restore-keys: |
            ballerina-deps-

      - name: Run Tests
        run: bal test

      # Optional: Docker Build and Push
      - name: Build Docker Image
        run: bal build --cloud=docker

      - name: Push Docker Image
        run: | # Replace my-ballerina-app with your Docker image name
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push my-ballerina-app:${{ github.sha }} 
