name: Ballerina CI/CD Pipeline - Deploy to Production

on:
  release:
    types: [released]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Tag and Push Docker Image
        run: | 
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull mohanvive/cerner-integration:latest
          docker tag mohanvive/cerner-integration:latest mohanvive/cerner-integration:${{ github.event.release.tag_name }}
          docker push mohanvive/cerner-integration:${{ github.event.release.tag_name }}
      
      - name: Install Kustomize
        run: |
          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      
      - name: Deploy to Cluster
        run: | 
          echo "$AZURE_CREDENTIALS" > config
          export KUBECONFIG=./config
          kubectl get ns
          pushd deployment/prod
          kustomize edit set image mohanvive/cerner-integration:latest=mohanvive/cerner-integration:${{ github.event.release.tag_name }}
          popd
          kustomize build deployment/prod > 
          kubectl apply -f deployment/prod/final.yaml -n prod
